### ISSUE TITLE
你好 我遇到一个问题

### ISSUE THREAD

**Issue by 18667366881** [JrDong/FitPopupWindow#2]
TabActivity  +  Fragment  +  ViewPager  + RecyclerView.Adapter   中的   	 mContext  似乎无效  之显示菜单不显示灰色半透明的背景是怎么回事  请帮忙看看 

FitPopupUtil fitPopupUtil = new FitPopupUtil((Activity) );
fitPopupUtil.setOnClickListener(new FitPopupUtil.OnCommitClickListener() {
						@Override
						public void onClick(String reason) {
							Log.e("显示效果","显示效果");
						}
					});
		fitPopupUtil.showPopup(v);

只能弹出菜单 但是没有灰色半透明的背景  请问是哪里的问题 谢谢

**Comment by JrDong** [comment]
你好，传一个activity对象试下

**Comment by 18667366881** [comment]
传了一个Activity   还是不行    我的嵌套层  太多了的原因吧    如果都用Fragment  嵌套显示是没问题的  但是  外层有2个Activty  可能是这个问题  我的层级是  TabActivity（第一层选项卡一共有4个子的选项卡HOMEActivity   DemoActivity   GoodsActivity   MeActivity）    有问题的是 HomeActivity + Fragment(循环添加了10个Fragment + ViewPager + RecyclerView.Adapter )（选项卡一个）   QQ 674483879  谢谢大神帮忙  弄了一周了

**Comment by JrDong** [comment]
你好，背景是下面这段代码：
 Window window = context.getWindow();
        WindowManager.LayoutParams lp = window.getAttributes();
        lp.alpha = 0.7f;
        window.setAttributes(lp);
可以调试一下看下是否是getwindow那里有问题，也有可能是部分厂商兼容性问题，可以说下你的手机型号和Api版本
