### ISSUE TITLE
你好 怎么修改  弹出的箭头的位置 

### ISSUE THREAD

**Issue by 18667366881** [JrDong/FitPopupWindow#3]
你好 怎么修改  弹出的箭头位置   
 就是弹出的那个小箭头的左右位置

**Comment by JrDong** [comment]
左右位置是根据目标view位置决定的，可以修改FitPopupWindow中的calculatePopWindowPos()方法mXCoordinate的计算。

**Comment by 18667366881** [comment]
谢谢
